### ISSUE TITLE
Avoid relative imports by making subdirectory "errors" a module

### ISSUE THREAD

**Issue by tisnik** [calebdehaan/codeDuplicationParser#82]
https://github.com/calebdehaan/codeDuplicationParser/blob/9abbe0cc7be34234720762588f3fdf38264330f7/code_duplication/src/preprocessing/repo_cloner.py#L7

If you add an `__init__.py` into the `errors`  subdirectory, it will became a proper module. Hence the relative imports (that are IMHO ugly) won't be necesarry.

**Comment by natiiix** [comment]
I agree the relative imports aren't very easy to read, but the make it easier for us to restructure the directory hierarchy, which has happened a few times before and it will happen again with #80. The missing `__init__.py` wasn't intentional. I must have just missed it. Is it possible to directly reference any module that has `__init__.py` in it as a base module (`errors.UserInputError` even though it's not in the root directory of the projet)?

**Comment by tisnik** [comment]
it is possible, and you can alter PYTHONPATH in case the structure gets more complicated.

Btw if we stop using relative imports it would be easy to move any module into separate library/package (which might happen later, I can imagine we'll export the matchers into its own library)
